version: '3.8'

services:
  web:
    build: ./djan

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./djan/:/servertest/

    ports:
      - 8000:8000

    env_file:
      - ./.env.dev