version: '3.8'

services:
  web:
    build: ./djan

    command: gunicorn servTest.wsgi:application --bind 0.0.0.0:8000

    expose:
      - 8000

    volumes:
      - ./djan/:/servertest

    ports:
      - 8000:8000

    env_file:
      - ./.env.dev

    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_volume: